name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray
  - cartopy
  - esmpy
  - intake-xarray
  - geopy
  - xesmf
  - esmf
  - xgcm
  - Ipython
  - xmitgcm
  - ffmpeg
